Info_355 = {'RomValid Flag msb': 85,
            'RomValid Flag lsb': 170,
            'Brightness Adjustment': 100,
            'DimmingType': 0,
            'Coordinate Shift X_bak': 255,
            'Coordinate Shift Y_bak': 255,
            'DimmingWhen0': 10,
            'DimmingFactor': 1,
            'gotoSleepDimmingTime': 50,
            'waiteForGotoSleep': 4,
            'p_log_dimmramape_L': [1, 4, 13, 26, 46],
            'p_log_dimmramape_H': [71, 105, 145, 196],
            'NAD_EOL': 1,
            'NAD_write': 255,
            'NAD_AA': 16,
            'NAD_Sel': 1,
            'short_R': 0,
            'short_G': 0,
            'short_B': 0,
            'open_R': 0,
            'open_G': 0,
            'open_B': 0,
            'error_RAM': 0,
            'error_ROM': 0,
            'error_NVM': 0,
            's_int_software_reset_cnt': 0,
            's_int_hardware_reset_cnt': 0,
            '产品型号': [56, 53, 68, 57, 52, 55, 51, 53, 53, 32],
            'HW ver': [72, 48, 50],
            'calibration_flag': 1,
            'brightness adjust': 100,
            }

Info_355A = {'RomValid Flag msb': 85,
             'RomValid Flag lsb': 170,
             'Brightness Adjustment': 100,
             'DimmingType': 0,
             'Coordinate Shift X_bak': 255,
             'Coordinate Shift Y_bak': 255,
             'DimmingWhen0': 10,
             'DimmingFactor': 1,
             'gotoSleepDimmingTime': 50,
             'waiteForGotoSleep': 4,
             'p_log_dimmramape_L': [1, 4, 13, 26, 46],
             'p_log_dimmramape_H': [71, 105, 145, 196],
             'NAD_EOL': 1,
             'NAD_write': 255,
             'NAD_AA': 16,
             'NAD_Sel': 1,
             'short_R': 0,
             'short_G': 0,
             'short_B': 0,
             'open_R': 0,
             'open_G': 0,
             'open_B': 0,
             'error_RAM': 0,
             'error_ROM': 0,
             'error_NVM': 0,
             's_int_software_reset_cnt': 0,
             's_int_hardware_reset_cnt': 0,
             '产品型号': [56, 53, 68, 57, 52, 55, 51, 53, 53, 65],
             'HW ver': [72, 48, 50],
             'calibration_flag': 1,
             'brightness adjust': 100,
             }

Info_355B = {'RomValid Flag msb': 85,
             'RomValid Flag lsb': 170,
             'Brightness Adjustment': 100,
             'DimmingType': 0,
             'Coordinate Shift X_bak': 255,
             'Coordinate Shift Y_bak': 255,
             'DimmingWhen0': 10,
             'DimmingFactor': 1,
             'gotoSleepDimmingTime': 50,
             'waiteForGotoSleep': 4,
             'p_log_dimmramape_L': [1, 4, 13, 26, 46],
             'p_log_dimmramape_H': [71, 105, 145, 196],
             'NAD_EOL': 1,
             'NAD_write': 255,
             'NAD_AA': 16,
             'NAD_Sel': 1,
             'short_R': 0,
             'short_G': 0,
             'short_B': 0,
             'open_R': 0,
             'open_G': 0,
             'open_B': 0,
             'error_RAM': 0,
             'error_ROM': 0,
             'error_NVM': 0,
             's_int_software_reset_cnt': 0,
             's_int_hardware_reset_cnt': 0,
             '产品型号': [56, 53, 68, 57, 52, 55, 51, 53, 53, 66],
             'HW ver': [72, 48, 50],
             'calibration_flag': 1,
             'brightness adjust': 100,
             }

Info_355C = {'RomValid Flag msb': 85,
             'RomValid Flag lsb': 170,
             'Brightness Adjustment': 100,
             'DimmingType': 0,
             'Coordinate Shift X_bak': 73,
             'Coordinate Shift Y_bak': 183,
             'DimmingWhen0': 10,
             'DimmingFactor': 1,
             'gotoSleepDimmingTime': 50,
             'waiteForGotoSleep': 4,
             'p_log_dimmramape_L': [1, 4, 13, 26, 46],
             'p_log_dimmramape_H': [71, 105, 145, 196],
             'NAD_EOL': 1,
             'NAD_write': 255,
             'NAD_AA': 16,
             'NAD_Sel': 1,
             'short_R': 0,
             'short_G': 0,
             'short_B': 0,
             'open_R': 0,
             'open_G': 0,
             'open_B': 0,
             'error_RAM': 0,
             'error_ROM': 0,
             'error_NVM': 0,
             's_int_software_reset_cnt': 0,
             's_int_hardware_reset_cnt': 0,
             '产品型号': [56, 53, 68, 57, 52, 55, 51, 53, 53, 67],
             'HW ver': [72, 48, 50],
             'calibration_flag': 1,
             'brightness adjust': 100,
             }